---
- name: 'Run OS Specific Patch'
  ansible.builtin.include_tasks: '{{ item }}'
  with_first_found:
    - '{{ ansible_facts[''distribution''] }}-{{ ansible_facts[''distribution_major_version''] }}.yaml'
    - '{{ ansible_facts[''distribution''] }}-{{ ansible_facts[''distribution_major_version''] }}.yml'
    - '{{ ansible_facts[''distribution''] }}.yaml'
    - '{{ ansible_facts[''distribution''] }}.yml'
    - '{{ ansible_facts[''os_family''] }}.yaml'
    - '{{ ansible_facts[''os_family''] }}.yml'
...
