---
- name: 'OS updates'
  hosts: '{{ target | default("all") }}'
  remote_user: 'root'
  gather_facts: true
  tasks:
    - name: 'Perform Host OS updates'
      ansible.builtin.include_role:
        name: 'p5xeu.general.os_update'
...
