---
galaxy_info:
  author: Lars Lehmann
  description: Install docker
  # company: p5x

  role_name: docker
  namespace: p5xeu

  license: BSD-3-Clause
  min_ansible_version: '2.16'
  platforms:
    - name: Debian
      versions:
        - bookworm

  galaxy_tags: []

dependencies: []
...
